# Generated by Django 4.2 on 2024-04-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
