# Generated by Django 4.2 on 2024-04-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_payment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
