# Generated by Django 4.2 on 2024-04-27 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_module', '0002_alter_order_is_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
