# Generated by Django 4.2 on 2024-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_remove_orderdetail_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_payment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
