# Generated by Django 4.2 on 2024-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.ManyToManyField(related_name='order-detail+', to='order_module.orderdetail'),
        ),
    ]
