# Generated by Django 4.2 on 2024-05-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_orderdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
    ]
